apiVersion: apps/v1
kind: Deployment # Specifies that this resource is a Deployment, used for managing a set of replicas of a pod.
metadata:
  name: decurb # Names this Deployment as "decurb".
spec:
  replicas: 2 # Indicates that two replicas (pods) of the application should be running.
  selector:
    matchLabels:
      app: decurb # The selector specifies that this Deployment targets pods with the label "app: decurb".
  template:
    metadata:
      labels:
        app: decurb # Labels the pods with "app: decurb" to match the selector.
    spec:
      containers:
        - name: decurb-container
          image: bseo97/decurb-full:v3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
      imagePullSecrets: # Specifies the secret to use for pulling private images from DockerHub.
        - name: regcred #  References a Kubernetes secret named "regcred".
---
apiVersion: v1
kind: Service # Specifies that this resource is a Service, which defines a logical set of pods and a policy to access them.
metadata:
  name: decurb-service # Names this Service as "decurb-service".
spec:
  selector:
    app: decurb # The selector specifies that this Service targets pods with the label "app: decurb".
  ports:
    - name: http
      port: 8080 # Exposes the service on port 8080.
  type: ClusterIP # Specifies that the service is of type ClusterIP, making it accessible only within the cluster.
